#**Lab 12 - Gram-Schmidt and QR decompositions**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.

In [1]:
# Do not edit this cell.

LabID="Lab12"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

**Enter your name, section number, and BYU NetID**

In [2]:
# Enter your first and last names in between the quotation marks.

first_name="Taylor"

last_name="Aydelotte"

# Enter your Math 215 section number in between the quotation marks.

section_number="001"

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER!

BYUNetID="aydeltay"

**Import NumPy**

In [3]:
import numpy as np

**Problem 1**

In [20]:
#This function reads in two vectors and outputs a boolean variable describing whether the two vectors are orthogonal.

def orthogonal_check(u,v):
  return np.allclose(np.dot(u, v), 0) # Put your return value here.

Check your function:

In [22]:
u = np.array([1, 2, -1, 4])
v = np.array([2, -2, -6, -1])

print(orthogonal_check(u,v))

x = np.array([1,1,1,1])
y = np.array([1,1,1,2])

print(orthogonal_check(x, y))

True
False


**Problem 2**

In [34]:
# This function reads in a list of vectors and checks whether they form an orthogonal set. Orthcheck should be a Boolean value (True or False).

def orth_set_check(vect_set):
  for i in range(len(vect_set)):
    for j in range(i + 1, len(vect_set)):
      if not orthogonal_check(vect_set[i], vect_set[j]):
        return False

  return True # Put your return value here.

Check your function:

In [28]:
p=[np.array([1,-1,0]),np.array([1,1,1]),np.array([0,1,-1])]
q=[np.array([1,0,0]),np.array([0,1,0]),np.array([0,0,1])]

orth_set_check(q)

True

**Problem 3**

In [33]:
# This function accepts a vector and returns a unit vector in the same direction.
import math

def normalize(v):
  mag = math.sqrt(sum(x**2 for x in v))
  if mag == 0:
    return v
  else:
    return [x / mag for x in v]

Check your function:

In [30]:
normalize(np.array([1,1,1,1]))

[0.5, 0.5, 0.5, 0.5]

**Problem 4**

In [35]:
# This function accepts two vectors a and b and returns the projection of a onto b.

def proj(a,b):
  dot_ab = sum(x * y for x, y in zip(a, b))
  mag_b_squared = (sum(x**2 for x in b) ** 0.5) ** 2

  projection = [x * dot_ab / mag_b_squared for x in b]
  return projection # Put your return value here.

Check your function:

In [32]:
a=np.array([1,4,1])
b=np.array([1,1,1])
proj(a,b)

[2.0000000000000004, 2.0000000000000004, 2.0000000000000004]

**Problem 5**

In [40]:
# This function accepts a list of linearly independent vectors V, and produces a new list X of orthonormal vectors which span the same space as a the vector of V.

def vector_subtraction(vector1, vector2):
  return [x - y for x, y in zip(vector1, vector2)]

def vector_scalar_multiply(vector, scalar):
  return [x * scalar for x in vector]

def magnitude(vector):
  return sum(x**2 for x in vector) ** 0.5

def gram_schmidt(V):
  X = []
  for i in range(len(V)):
    x_i = V[i].copy()
    for j in range(i):
      proj = vector_scalar_multiply(X[j], np.dot(V[i], X[j]) / magnitude(X[j]) ** 2)
      x_i = vector_subtraction(x_i, proj)
    X.append(x_i)

  for i in range(len(X)):
    X[i] = vector_scalar_multiply(X[i], 1 / magnitude(X[i]))

  return X # Put your return value here.

Check your function:

In [41]:
L=[np.array([1,3,2,4,0]),np.array([-1,0,4,5,0]),np.array([0,2,2,2,2]),np.array([3,2,3,2,0])]
A=gram_schmidt(L)
print(orth_set_check(A))
A

True


[[0.18257418583505536,
  0.5477225575051661,
  0.3651483716701107,
  0.7302967433402214,
  0.0],
 [-0.45161355411445187,
  -0.6417666295310632,
  0.5229209573956812,
  0.3327678819790698,
  0.0],
 [-0.18160984190580073,
  0.2118781488901009,
  0.257280609366551,
  -0.2421464558744009,
  0.8929150560368535],
 [0.727825342874051,
  -0.20795009796401456,
  0.5718627694010399,
  -0.31192514694602186,
  -0.051987524491003675]]

**Problem 6**

In [38]:
# This function accepts a matrix A as a 2D NumPy Array, and returns two new matrices Q and R.

def QR_decomposition(A):
  m, n = A.shape
  Q = np.zeros((m, n))
  R = np.zeros((n, n))

  for j in range(n):
    v = A[:, j]
    for i in range(j):
      R[i, j] = np.dot(Q[:, i], A[:, j])
      v = vector_subtraction(v, vector_scalar_multiply(Q[:, i], R[i, j]))
    R[j, j] = magnitude(v)
    Q[:, j] = vector_scalar_multiply(v, 1 / R[j, j])
  return Q,R # Put your return value here.  The return line should look like:  return Q,R

Check your function:

In [39]:
A=np.transpose(np.array([[1,3,2,4,0],[-1,0,4,5,0],[0,2,2,2,2],[3,2,3,2,0]]))
np.shape(A)[1]
Q,R=QR_decomposition(A)

print(Q)
print(R)

[[ 0.18257419 -0.45161355 -0.18160984  0.72782534]
 [ 0.54772256 -0.64176663  0.21187815 -0.2079501 ]
 [ 0.36514837  0.52292096  0.25728061  0.57186277]
 [ 0.73029674  0.33276788 -0.24214646 -0.31192515]
 [ 0.          0.          0.89291506 -0.05198752]]
[[ 5.47722558  4.92950302  3.28633535  4.19920627]
 [ 0.          4.20713679  0.42784442 -0.40407529]
 [ 0.          0.          2.23985472  0.16647569]
 [ 0.          0.          0.          2.85931385]]


We can check to see if QR=A, after rounding with the following command:

In [42]:
np.round(np.matmul(Q,R))

array([[ 1., -1., -0.,  3.],
       [ 3., -0.,  2.,  2.],
       [ 2.,  4.,  2.,  3.],
       [ 4.,  5.,  2.,  2.],
       [ 0.,  0.,  2., -0.]])

**Problem 7**

In [52]:
# This Function was created in Lab 5.  It accepts an upper triangular square matrix U and a vector b, solves Ux=b for x.  You may use it in the function QR_solver.

def back_substitution(U,b):
  n=len(b)
  x=np.array([0.0 for i in range(n)])
  for i in range(n-1,-1, -1):
    r=(b[i]-sum([x[j]*U[i][j] for j in range(i+1,n)]))/U[i][i]
    x[i]=r
  return x

In [63]:
# This function accepts an invertible matrix A and a vector b, solves Ax=b for x.

def QR_solver(A,b):
  Q,R = QR_decomposition(A)
  y = np.linalg.inv(Q) @ b
  x = back_substitution(R, y)
  return x # Put your return value here.

In [64]:
A=np.array([[3,1,-2],[1.5,2,-5],[2,-4,1]])
b=np.array([1.1,3,-2])
QR_solver(A,b)

array([-0.07032967,  0.34395604, -0.48351648])

**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.  

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to http://www.math.byu.edu:30000 for grading.